### ISSUE TITLE
Can't get metadata

### ISSUE THREAD

**Issue by Aces-and-Jacks** [nonpricklycactus/Ehentai_metadata#14]
I tried the plugin but it doesn't work. I used gallery-dl to download and turn into .cbz format. in calibre I edited to show the url, but the plugin won't work. Maybe I did something wrong in setting it up but I don't know. If this is still maintained would you be able to help me?

**Comment by nonpricklycactus** [comment]
I need more detailed information, please send over your plugin configuration along with the names and URLs of the comics you are unable to download.
Make sure to blur out any account information.

**Comment by Aces-and-Jacks** [comment]
https://e-hentai.org/g/2128426/07926fa934/

<img width="604" alt="Screen Shot 2024-04-25 at 11 31 25 PM" src="https://github.com/nonpricklycactus/Ehentai_metadata/assets/106651342/6239d38e-6502-4f94-beec-3db32c050cbf">
<img width="842" alt="Screen Shot 2024-04-25 at 11 32 05 PM" src="https://github.com/nonpricklycactus/Ehentai_metadata/assets/106651342/881d4c4a-e7aa-4a01-9456-66da97e449f4">

**Comment by nonpricklycactus** [comment]
This is because the plugin did not find the corresponding comic; the plugin's name search is not very precise and often fails to find the correct comic. You can manually obtain the metadata for the corresponding comic using the following method.
![image](https://github.com/nonpricklycactus/Ehentai_metadata/assets/36537993/2ed380c9-ee1b-41f7-ae5f-58e9e5abb17c)
When downloading the metadata, a window will pop up. Enter the URL of the corresponding comic in the URL field and click the button to manually retrieve the metadata for that comic.
![image](https://github.com/nonpricklycactus/Ehentai_metadata/assets/36537993/6708628b-507d-4d29-bf28-eb79a98e5a6d)

**Comment by Aces-and-Jacks** [comment]
Thank you

**Comment by Aces-and-Jacks** [comment]
<img width="604" alt="Screen Shot 2024-04-27 at 1 48 07 AM" src="https://github.com/nonpricklycactus/Ehentai_metadata/assets/106651342/f1192ad9-eea9-4d4b-a346-75461c84b6d2">

**Comment by Aces-and-Jacks** [comment]
Did what you did and this happened

**Comment by nonpricklycactus** [comment]
In my version 7.9.0, there are no issues. You can try upgrading Calibre to see if that resolves the problem.

**Comment by Aces-and-Jacks** [comment]
yeah...that's probably gonna anchor this issue for me. I can't update due to a system OS compatibility, which is just me not wanting to have a massive UI/UX change. 

So I guess this issue can be closed unless someone else comes along with a MacOS issue
